import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Import NuqsAdapter from the Nuqs library to use it for the search functionality
import { NuqsAdapter } from "nuqs/adapters/next/app";

// Convex Client Provider is a component that provides the Convex client to the rest of the application
import { ConvexClientProvider } from "@/components/convex-client-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description:
    "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NuqsAdapter>
          <ConvexClientProvider>
            {children}
          </ConvexClientProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
